// AI Executive Morning Brief — modal component
interface Props { onClose: () => void; }

const now = new Date();
const dateStr = now.toLocaleDateString('en-ZA', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

export default function ExecutiveBrief({ onClose }: Props) {
  const handlePrint = () => window.print();

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 600, display: 'flex', alignItems: 'center', justifyContent: 'center',
      background: 'rgba(0,0,0,0.8)', backdropFilter: 'blur(8px)', padding: 20,
    }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div style={{
        background: 'linear-gradient(140deg,#0A101E,#080D18)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 20, width: '100%', maxWidth: 680, maxHeight: '90vh', overflowY: 'auto',
        boxShadow: '0 40px 100px rgba(0,0,0,0.7)',
      }}>
        {/* Header */}
        <div style={{ padding: '24px 28px', borderBottom: '1px solid rgba(255,255,255,0.07)', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, color: '#0EA5E9', letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 4 }}>🤖 AI EXECUTIVE BRIEF</div>
            <h2 style={{ fontFamily: 'Outfit, sans-serif', fontSize: 22, fontWeight: 900, color: '#F0F6FF', margin: 0 }}>Good morning, Malcolm</h2>
            <div style={{ fontSize: 12, color: '#8B949E', marginTop: 4 }}>{dateStr} · Automatically generated by PayGuard AI</div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button onClick={handlePrint} style={{ padding: '7px 14px', borderRadius: 8, background: 'rgba(14,165,233,0.1)', border: '1px solid rgba(14,165,233,0.3)', color: '#0EA5E9', fontSize: 11, fontWeight: 700, cursor: 'pointer' }}>🖨️ Print / PDF</button>
            <button onClick={onClose} style={{ padding: '7px 14px', borderRadius: 8, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', color: '#64748B', fontSize: 11, cursor: 'pointer' }}>✕ Close</button>
          </div>
        </div>

        <div style={{ padding: '22px 28px', display: 'flex', flexDirection: 'column', gap: 20 }}>
          {/* Headline summary */}
          <div style={{ padding: '18px 20px', background: 'rgba(14,165,233,0.06)', border: '1px solid rgba(14,165,233,0.15)', borderRadius: 14 }}>
            <div style={{ fontSize: 10, fontWeight: 700, color: '#0EA5E9', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 10 }}>Executive Summary</div>
            <p style={{ fontSize: 14, color: '#94A3B8', lineHeight: 1.85, margin: 0 }}>
              Last night, PayGuard evaluated <strong style={{ color: '#F0F6FF' }}>847 transactions</strong> across your customer base and automatically blocked <strong style={{ color: '#EF4444' }}>47 fraud attempts</strong>, saving your institution an estimated <strong style={{ color: '#10F5A0' }}>R124,000</strong>. A new mule network (<strong style={{ color: '#F97316' }}>RING-003</strong>) was detected in Durban at 02:14 AM, linking 3 accounts through a shared device fingerprint. All three accounts have been frozen pending your review.
            </p>
          </div>

          {/* KPI grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 12 }}>
            {[
              { label: 'Transactions evaluated', value: '847', color: '#0EA5E9', icon: '📊' },
              { label: 'Fraud attempts blocked', value: '47', color: '#EF4444', icon: '🚨' },
              { label: 'Fraud prevented', value: 'R124,000', color: '#10F5A0', icon: '🛡️' },
              { label: 'New fraud rings', value: '1', color: '#F97316', icon: '🕸️' },
              { label: 'Accounts frozen', value: '3', color: '#FBBF24', icon: '🔒' },
              { label: 'Avg decision time', value: '71ms', color: '#7C3AED', icon: '⚡' },
            ].map(k => (
              <div key={k.label} style={{ padding: '14px 16px', background: 'rgba(255,255,255,0.07)', border: `1px solid ${k.color}20`, borderRadius: 12 }}>
                <div style={{ fontSize: 18, marginBottom: 4 }}>{k.icon}</div>
                <div style={{ fontSize: 18, fontWeight: 800, color: k.color, fontFamily: 'Outfit', marginBottom: 2 }}>{k.value}</div>
                <div style={{ fontSize: 10, color: '#8B949E' }}>{k.label}</div>
              </div>
            ))}
          </div>

          {/* Top threats */}
          <div>
            <div style={{ fontSize: 11, fontWeight: 700, color: '#8B949E', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 12 }}>🔥 Top Threats Last Night</div>
            {[
              { time: '23:14', threat: 'Vishing cluster — Gauteng', detail: '18 transactions flagged · 18 blocked · R47,200 protected', color: '#EF4444', badge: 'BLOCKED' },
              { time: '01:33', threat: 'SIM swap attempt — Western Cape', detail: '2 accounts · USSD push sent · Both confirmed legitimate', color: '#FBBF24', badge: 'RESOLVED' },
              { time: '02:14', threat: 'New mule network — RING-003 Durban', detail: '3 accounts sharing DEV-99f · All frozen · Analyst review required', color: '#F97316', badge: 'REVIEW' },
              { time: '04:55', threat: 'OTP intercept attempt — Sandton', detail: 'Screen capture overlay detected · Payment blocked · R15,000 saved', color: '#EF4444', badge: 'BLOCKED' },
            ].map(t => (
              <div key={t.time} style={{ display: 'flex', gap: 14, padding: '11px 0', borderBottom: '1px solid rgba(255,255,255,0.05)', alignItems: 'flex-start' }}>
                <div style={{ fontFamily: 'JetBrains Mono', fontSize: 10, color: '#64748B', width: 40, flexShrink: 0, paddingTop: 2 }}>{t.time}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: '#F0F6FF', marginBottom: 3 }}>{t.threat}</div>
                  <div style={{ fontSize: 11, color: '#64748B' }}>{t.detail}</div>
                </div>
                <span style={{ fontSize: 9, padding: '3px 8px', borderRadius: 99, background: `${t.color}15`, border: `1px solid ${t.color}30`, color: t.color, fontWeight: 700, flexShrink: 0 }}>{t.badge}</span>
              </div>
            ))}
          </div>

          {/* AI Recommendations */}
          <div style={{ padding: '18px 20px', background: 'rgba(124,58,237,0.06)', border: '1px solid rgba(124,58,237,0.2)', borderRadius: 14 }}>
            <div style={{ fontSize: 10, fontWeight: 700, color: '#7C3AED', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>🤖 AI Recommended Actions Today</div>
            {[
              { priority: 'P1', action: 'Review RING-003 (Durban) — 3 frozen accounts awaiting analyst decision', color: '#EF4444' },
              { priority: 'P2', action: 'Tighten RULE_009 threshold from 0.75 → 0.85 (current false positive headroom: 1.7%)', color: '#F97316' },
              { priority: 'P3', action: 'Friday forecast shows 48-attack peak — consider scheduling additional analyst shift', color: '#FBBF24' },
              { priority: 'P4', action: 'Update SDK to v1.1.0 on Mobile Money integration for enhanced USSD push support', color: '#0EA5E9' },
            ].map(r => (
              <div key={r.priority} style={{ display: 'flex', gap: 10, marginBottom: 8, alignItems: 'flex-start' }}>
                <span style={{ fontSize: 9, padding: '2px 7px', borderRadius: 4, background: `${r.color}15`, border: `1px solid ${r.color}30`, color: r.color, fontWeight: 700, flexShrink: 0, marginTop: 1, fontFamily: 'JetBrains Mono' }}>{r.priority}</span>
                <span style={{ fontSize: 12, color: '#64748B', lineHeight: 1.6 }}>{r.action}</span>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div style={{ textAlign: 'center', fontSize: 10, color: '#64748B', paddingTop: 4 }}>
            Generated by PayGuard AI · {dateStr} · payguard.africa · For internal distribution only
          </div>
        </div>
      </div>
    </div>
  );
}
